CREATE TABLE short_selling (
    short_selling_id BIGINT NOT NULL AUTO_INCREMENT,
    stock_id BIGINT NOT NULL,
    report_date DATE NOT NULL,
    market_code VARCHAR(20) NOT NULL,
    security_type VARCHAR(30) NOT NULL,
    short_volume_total DECIMAL(20,0) NULL,
    short_volume_uptick_applied DECIMAL(20,0) NULL,
    short_volume_uptick_exempt DECIMAL(20,0) NULL,
    total_volume DECIMAL(20,0) NULL,
    short_volume_ratio DECIMAL(10,6) NULL,
    short_amount_total DECIMAL(20,0) NULL,
    short_amount_uptick_applied DECIMAL(20,0) NULL,
    short_amount_uptick_exempt DECIMAL(20,0) NULL,
    total_amount DECIMAL(20,0) NULL,
    short_amount_ratio DECIMAL(10,6) NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'KRX',
    source_screen_id VARCHAR(20) NOT NULL DEFAULT 'MDCSTAT301',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (short_selling_id),
    UNIQUE KEY uk_short_selling_stock_date (stock_id, report_date),
    KEY idx_short_selling_report_date (report_date),
    KEY idx_short_selling_market_date (market_code, report_date),
    CONSTRAINT fk_short_selling_stock FOREIGN KEY (stock_id) REFERENCES stock (stock_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
