CREATE TABLE issued_shares (
    issued_shares_id BIGINT NOT NULL AUTO_INCREMENT,
    stock_id BIGINT NOT NULL,
    rcept_no VARCHAR(14) NOT NULL,
    corp_cls VARCHAR(1) NULL,
    corp_code VARCHAR(8) NOT NULL,
    corp_name VARCHAR(255) NULL,
    share_type VARCHAR(50) NOT NULL,
    authorized_shares BIGINT NULL,
    issued_shares_to_date BIGINT NULL,
    decreased_shares_to_date BIGINT NULL,
    decreased_by_reduction BIGINT NULL,
    decreased_by_profit_incineration BIGINT NULL,
    decreased_by_redemption BIGINT NULL,
    decreased_by_other BIGINT NULL,
    issued_shares_total BIGINT NULL,
    treasury_shares BIGINT NULL,
    floating_shares BIGINT NULL,
    base_date DATE NOT NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'OPENDART',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (issued_shares_id),
    UNIQUE KEY uk_issued_shares_stock_date_type (stock_id, base_date, share_type),
    KEY idx_issued_shares_stock_date (stock_id, base_date),
    KEY idx_issued_shares_corp_code_date (corp_code, base_date),
    CONSTRAINT fk_issued_shares_stock FOREIGN KEY (stock_id) REFERENCES stock (stock_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
