CREATE TABLE bond_yield (
    bond_yield_id BIGINT NOT NULL AUTO_INCREMENT,
    yield_date DATE NOT NULL,
    raw_time VARCHAR(16) NOT NULL,
    cycle VARCHAR(1) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    instrument_code VARCHAR(20) NOT NULL,
    instrument_name VARCHAR(100) NOT NULL,
    maturity_months INT NULL,
    yield_value DECIMAL(10,6) NOT NULL,
    unit_name VARCHAR(20) NOT NULL,
    stat_code VARCHAR(20) NOT NULL,
    stat_name VARCHAR(255) NOT NULL,
    item_code VARCHAR(20) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'BOK_ECOS',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (bond_yield_id),
    UNIQUE KEY uk_bond_yield_source_instrument_cycle_time (source, instrument_code, cycle, raw_time),
    KEY idx_bond_yield_yield_date (yield_date),
    KEY idx_bond_yield_instrument_date (instrument_code, yield_date),
    KEY idx_bond_yield_country_date (country_code, yield_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
