CREATE TABLE stock_investor_flow (
    stock_investor_flow_id BIGINT NOT NULL AUTO_INCREMENT,
    stock_id BIGINT NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    trade_date DATE NOT NULL,
    market_div_code VARCHAR(8) NOT NULL DEFAULT 'J',
    close_price DECIMAL(20,4) NULL,
    accumulated_volume DECIMAL(24,0) NULL,
    accumulated_trading_value_million DECIMAL(24,0) NULL,
    foreign_net_buy_qty DECIMAL(24,0) NULL,
    foreign_net_buy_value_million DECIMAL(24,0) NULL,
    individual_net_buy_qty DECIMAL(24,0) NULL,
    individual_net_buy_value_million DECIMAL(24,0) NULL,
    institution_net_buy_qty DECIMAL(24,0) NULL,
    institution_net_buy_value_million DECIMAL(24,0) NULL,
    securities_net_buy_qty DECIMAL(24,0) NULL,
    securities_net_buy_value_million DECIMAL(24,0) NULL,
    investment_trust_net_buy_qty DECIMAL(24,0) NULL,
    investment_trust_net_buy_value_million DECIMAL(24,0) NULL,
    private_fund_net_buy_qty DECIMAL(24,0) NULL,
    private_fund_net_buy_value_million DECIMAL(24,0) NULL,
    bank_net_buy_qty DECIMAL(24,0) NULL,
    bank_net_buy_value_million DECIMAL(24,0) NULL,
    insurance_net_buy_qty DECIMAL(24,0) NULL,
    insurance_net_buy_value_million DECIMAL(24,0) NULL,
    fund_net_buy_qty DECIMAL(24,0) NULL,
    fund_net_buy_value_million DECIMAL(24,0) NULL,
    other_net_buy_qty DECIMAL(24,0) NULL,
    other_net_buy_value_million DECIMAL(24,0) NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'KIS',
    source_tr_id VARCHAR(20) NOT NULL DEFAULT 'FHPTJ04160001',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (stock_investor_flow_id),
    UNIQUE KEY uk_stock_investor_flow_stock_date_source (stock_id, trade_date, source),
    KEY idx_stock_investor_flow_code_date (stock_code, trade_date),
    KEY idx_stock_investor_flow_trade_date (trade_date),
    CONSTRAINT fk_stock_investor_flow_stock FOREIGN KEY (stock_id) REFERENCES stock (stock_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
