CREATE TABLE analysis_report (
    report_id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    feature_type VARCHAR(20) NOT NULL,
    subject_type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    stock_code VARCHAR(32) NULL,
    company_name VARCHAR(255) NULL,
    portfolio_summary VARCHAR(500) NULL,
    analysis_model VARCHAR(100) NULL,
    invest_level VARCHAR(30) NULL,
    risk_profile VARCHAR(50) NULL,
    analysis_window VARCHAR(50) NULL,
    price_basis VARCHAR(50) NULL,
    generated_at DATETIME(6) NOT NULL,
    data_as_of VARCHAR(100) NULL,
    request_payload_json JSON NOT NULL,
    result_snapshot_json JSON NOT NULL,
    warnings_json JSON NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (report_id),
    KEY idx_analysis_report_user_generated (user_id, generated_at),
    KEY idx_analysis_report_feature (feature_type, generated_at),
    KEY idx_analysis_report_stock (stock_code, generated_at),
    CONSTRAINT fk_analysis_report_user FOREIGN KEY (user_id) REFERENCES users (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
