package com.qaima.common;

public enum Feat2WarningCode {

    // ----- 종목 / 산업 -----
    STOCK_NOT_FOUND,
    INDUSTRY_MISSING,

    // ----- 산업지수 (FR-17) -----
    INDUSTRY_INDEX_MISSING,
    INDUSTRY_INDEX_OHLCV_EMPTY,
    INDUSTRY_INDEX_SAVE_FAILED,
    INDUSTRY_INDEX_FETCH_FAILED,

    // ----- 유사 종목 / 클러스터 (FR-18) -----
    PEER_CLUSTER_CACHE_MISS,
    PEER_CLUSTER_EMPTY,
    PEER_CLUSTER_MISSING,
    PEER_CLUSTER_DB_EMPTY,
    PEER_CLUSTER_CACHE_READ_FAILED,
    PEER_CLUSTER_CACHE_WRITE_FAILED,
    PEER_CLUSTER_DB_READ_FAILED,
    PEER_CLUSTER_JSON_PARSE_FAILED,
    PEER_CLUSTER_INTERNAL_ERROR,
    PEER_CLUSTER_LOAD_FAILED,
    PEER_CLUSTER_INDUSTRY_ID_MISSING,
    PEER_CLUSTER_ANCHOR_MISSING,
    PEER_CLUSTER_LOW_POSITIVE_CORR_CANDIDATES,
    INDUSTRY_ADJUSTED_RETURN_FALLBACK_RAW,
    PEER_CORR_STABILITY_INSUFFICIENT_DATA,
    PEER_FILTER_RELAXED,
    PEER_CANDIDATES_LOW_AFTER_QUALITY_FILTER,
    PEER_CANDIDATES_LOW_AFTER_LIQUIDITY_FILTER,
    PEER_CANDIDATES_LOW_AFTER_VOLATILITY_FILTER,
    PEER_COUNT_REDUCED_BY_CANDIDATE_SIZE,
    PEER_CANDIDATES_INSUFFICIENT,
    PEER_DISPLAY_CANDIDATES_LOW,

    // ----- 뉴스 / 감성 -----
    NEWS_NOT_FOUND,
    SENTIMENT_NOT_FOUND,

    // ----- 공매도 -----
    SHORT_SELLING_MISSING,
    SHORT_SELLING_LOAD_FAILED,

    // ----- 기준금리 -----
    BASE_RATE_MISSING,
    BASE_RATE_LOAD_FAILED,

    // ----- 외부 연동 / 대체 처리 -----
    EXTERNAL_API_FALLBACK_USED,

    // ----- LLM -----
    LLM_EXPLAIN_FAILED,

    // ----- Feat2 (최상위) -----
    FEAT2_INTERNAL_ERROR
}
