analysis:
  base-url: "http://localhost:8000"

auth:
  cookie:
    refresh-token-name: qaima_refresh_token
    path: "/api/v1/auth"
    same-site: "Lax"
    secure: false
    http-only: true

opendart:
  base-url: "https://opendart.fss.or.kr/api"
  sync:
    enabled: true
    daily-cron: "0 10 3 * * *"

spring:
  profiles:
    active: mysql #h2 <-> mysql 변경해서 사용

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  config:
    import: optional:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: never

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2s

logging:
  level:
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    org.springframework: DEBUG
    com.qaima: DEBUG
