const isEnglishLanguage = (language?: string | null) => (language ?? "").toLowerCase().startsWith("en");

const EN_BACKEND_TEXT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/기능1\s*종목\s*분석\s*리포트/g, "Feature 1 Stock Analysis Report"],
  [/기능2\s*외부요인\s*분석\s*리포트/g, "Feature 2 External Factors Report"],
  [/기능2\s*외부요인\s*리포트/g, "Feature 2 External Factors Report"],
  [/기능3\s*포트폴리오\s*분석\s*리포트/g, "Feature 3 Portfolio Analysis Report"],
  [/외\s*(\d+)\s*개\s*종목/g, "and $1 more holding(s)"],
  [/유사\s*종목군/g, "peer group"],
  [/유사\s*종목/g, "peer stocks"],
  [/보조\s*관측/g, "overlay observations"],
  [/최적화\s*관측/g, "optimization view"],
  [/핵심\s*리스크/g, "core risk"],
  [/현재\s*포트폴리오/g, "current portfolio"],
  [/현재\s*구성/g, "current portfolio"],
  [/가격\s*시계열/g, "price series"],
  [/포트폴리오\s*분석/g, "portfolio analysis"],
  [/분산\s*리스크/g, "diversification risk"],
  [/위험\s*기여도/g, "risk contribution"],
  [/투자\s*성향/g, "risk profile"],
  [/목표\s*변동성/g, "target volatility"],
  [/변동성/g, "volatility"],
  [/종목\s*건강도/g, "stock quality"],
  [/확대\s*압력/g, "expansion pressure"],
  [/관찰\s*압력/g, "observation pressure"],
  [/동행\s*참고/g, "co-movement reference"],
  [/관찰\s*압력/g, "observation pressure"],
  [/성향\s*대비\s*높은\s*변동\s*위험/g, "High volatility risk versus profile"],
  [/특정\s*종목\s*위험\s*기여\s*집중/g, "Concentrated risk contribution from a specific holding"],
  [/삼성전자/g, "Samsung Electronics"],
  [/SK하이닉스/g, "SK hynix"],
  [/KRW\s*현금/g, "KRW cash"],
  [/현금/g, "cash"],
  [/공격적/g, "aggressive"],
  [/안정적/g, "conservative"],
  [/중립형/g, "balanced"],
  [/공격형/g, "aggressive"],
  [/보수형/g, "conservative"],
  [/균형형/g, "balanced"],
  [/기준\s*시각/g, "reference time"],
  [/최근\s*결과/g, "recent result"],
  [/새로\s*분석/g, "re-analyze"],
  [/새\s*분석/g, "new analysis"],
  [/기존\s*source\s*data/g, "existing source data"],
  [/원천\s*데이터/g, "source data"],
  [/업종\s*정보/g, "industry information"],
  [/산업\s*집중도\s*관측/g, "industry concentration observation"],
  [/산업\s*지수/g, "industry index"],
  [/산업지수/g, "industry index"],
  [/유사종목/g, "peer stocks"],
  [/캐시/g, "cache"],
  [/크레딧/g, "credit"],
  [/성향보다 공격적/g, "more aggressive than profile"],
  [/성향보다 안정적/g, "more conservative than profile"],
  [/목표 변동성 초과/g, "above target volatility"],
  [/위험 기여도 높음/g, "high risk contribution"],
  [/\bAGGRESSIVE_THAN_PROFILE\b/g, "more aggressive than profile"],
  [/\bCONSERVATIVE_THAN_PROFILE\b/g, "more conservative than profile"],
  [/\bABOVE_TARGET_VOLATILITY\b/g, "above target volatility"],
  [/\bHIGH_RISK_CONTRIBUTION\b/g, "high risk contribution"],
  [/Core 분석만 실행하면 1 credit이 차감됩니다\./g, "Running core analysis only deducts 1 credit."],
  [/Core 분석은 1 credit이며, cache가 없는 체크 항목마다 1 credit이 추가됩니다\./g, "Core analysis costs 1 credit, and each selected item without cache adds 1 credit."],
  [/Core analysis costs 1 credit이며, cache가 없는 체크 항목마다 1 credit이 추가됩니다\./g, "Core analysis costs 1 credit, and each selected item without cache adds 1 credit."],
  [/최근 result가 있지만 re-analyze하도록 선택되어 1 credit이 추가됩니다\./g, "A recent result exists, but re-analysis was selected, so 1 credit is added."],
  [/최근 결과가 있지만 새로 분석하도록 선택되어 1 credit이 추가됩니다\./g, "A recent result exists, but re-analysis was selected, so 1 credit is added."],
  [/기존 source data를 재사용할 수 있어 추가 credit이 필요하지 않습니다\./g, "Existing source data can be reused, so no additional credit is required."],
  [/기존 원천 데이터를 재사용할 수 있어 추가 credit이 필요하지 않습니다\./g, "Existing source data can be reused, so no additional credit is required."],
  [/원천 데이터가 부족해 새로 분석하며 1 credit이 추가됩니다\./g, "Source data is insufficient, so new analysis adds 1 credit."],
  [/보유 종목의 업종 정보를 사용해 산업 집중도 관측을 반영합니다\./g, "Uses the holdings' industry information to reflect industry concentration observations."],
  [/최근 뉴스 최대 (\d+)개의 Feature2 news sentiment 데이터를 core risk와 분리된 뉴스 흐름 참고 정보로 표시합니다\./g, "Shows up to $1 recent Feature2 news sentiment items as separate news-flow context, outside core risk."],
];

export function localizeBackendText(value?: string | null, language?: string | null): string {
  if (!value) return "";
  if (!isEnglishLanguage(language)) return value;
  return EN_BACKEND_TEXT_REPLACEMENTS.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}
