const isEnglishLanguage = (language?: string | null) => (language ?? "").toLowerCase().startsWith("en");

const EN_BACKEND_TEXT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/기능1\s*종목\s*분석\s*리포트/g, "Feature 1 Stock Analysis Report"],
  [/기능2\s*외부요인\s*분석\s*리포트/g, "Feature 2 External Factors Report"],
  [/기능2\s*외부요인\s*리포트/g, "Feature 2 External Factors Report"],
  [/기능3\s*포트폴리오\s*분석\s*리포트/g, "Feature 3 Portfolio Analysis Report"],
  [/외\s*(\d+)\s*개\s*종목/g, "and $1 more holding(s)"],
  [/가격\s*시계열\s*기반\s*현재\s*포트폴리오\s*분석입니다\./g, "This is the current portfolio analysis based on price series."],
  [/가격\s*시계열이\s*부족해\s*입력\s*평가금액\s*비중\s*기준\s*임시\s*분석을\s*표시합니다\./g, "Price-series data is insufficient, so a temporary analysis based on input valuation weights is shown."],
  [/공통\s*거래일이\s*부족해\s*입력\s*평가금액\s*비중\s*기준\s*임시\s*분석을\s*표시합니다\./g, "Common trading days are insufficient, so a temporary analysis based on input valuation weights is shown."],
  [/평가금액을\s*계산할\s*수\s*없어\s*입력\s*평가금액\s*비중\s*기준\s*임시\s*분석을\s*표시합니다\./g, "Valuation cannot be calculated, so a temporary analysis based on input valuation weights is shown."],
  [/안정형\s*목표\s*변동성\s*([0-9.]+%)에\s*맞춘\s*제약\s*기반\s*비교\s*포트폴리오입니다\./g, "This is a constraint-based comparison portfolio aligned to the stable target volatility ($1)."],
  [/균형형\s*목표\s*변동성\s*([0-9.]+%)에\s*맞춘\s*제약\s*기반\s*비교\s*포트폴리오입니다\./g, "This is a constraint-based comparison portfolio aligned to the balanced target volatility ($1)."],
  [/공격형\s*목표\s*변동성\s*([0-9.]+%)에\s*맞춘\s*제약\s*기반\s*비교\s*포트폴리오입니다\./g, "This is a constraint-based comparison portfolio aligned to the aggressive target volatility ($1)."],
  [/심리형\s*목표\s*변동성\s*([0-9.]+%)에\s*맞춘\s*제약\s*기반\s*비교\s*포트폴리오입니다\./g, "This is a constraint-based comparison portfolio aligned to the psychological-profile target volatility ($1)."],
  [/안정형\s*목표\s*변동성\s*기준\s*임시\s*비교\s*포트폴리오입니다\./g, "This is a temporary comparison portfolio based on the stable target volatility."],
  [/균형형\s*목표\s*변동성\s*기준\s*임시\s*비교\s*포트폴리오입니다\./g, "This is a temporary comparison portfolio based on the balanced target volatility."],
  [/공격형\s*목표\s*변동성\s*기준\s*임시\s*비교\s*포트폴리오입니다\./g, "This is a temporary comparison portfolio based on the aggressive target volatility."],
  [/심리형\s*목표\s*변동성\s*기준\s*임시\s*비교\s*포트폴리오입니다\./g, "This is a temporary comparison portfolio based on the psychological-profile target volatility."],
  [/성향\s*대비\s*높은\s*변동\s*위험/g, "High volatility risk versus profile"],
  [/성향\s*대비\s*낮은\s*변동\s*위험/g, "Low volatility risk versus profile"],
  [/특정\s*종목\s*위험\s*기여\s*집중/g, "Concentrated risk contribution from a specific holding"],
  [/성향\s*기준에\s*가까운\s*구성/g, "Allocation close to profile"],
  [/현재\s*구성의\s*가격\s*변동\s*폭이\s*투자\s*성향\s*기준보다\s*큽니다\./g, "The current portfolio's price volatility is higher than the risk-profile benchmark."],
  [/현재\s*구성은\s*투자\s*성향\s*기준보다\s*안정적으로\s*움직이는\s*편입니다\./g, "The current portfolio is moving more conservatively than the risk-profile benchmark."],
  [/현재\s*포트폴리오의\s*변동\s*위험이\s*투자\s*성향\s*기준과\s*크게\s*벗어나지\s*않습니다\./g, "The current portfolio's volatility risk is broadly aligned with the risk-profile benchmark."],
  [/([^.\s]+)\s*비중이\s*전체\s*위험에서\s*차지하는\s*몫이\s*큽니다\./g, "$1 accounts for a large share of total portfolio risk."],
  [/종목\s*건강도\s*:\s*확대\s*압력/g, "Stock Quality: Expansion Pressure"],
  [/종목\s*건강도\s*:\s*축소\s*압력/g, "Stock Quality: Reduction Pressure"],
  [/종목\s*건강도\s*:\s*관찰\s*압력/g, "Stock Quality: Observation Pressure"],
  [/내부\s*분산\s*리스크/g, "Internal Diversification Risk"],
  [/기술\s*흐름\s*시나리오/g, "Technical Trend Scenario"],
  [/뉴스\s*리스크\s*시나리오/g, "News Risk Scenario"],
  [/분산\s*보강\s*시나리오/g, "Diversification Reinforcement Scenario"],
  [/보조\s*관측\s*균형\s*시나리오/g, "Balanced Overlay Scenario"],
  [/가격\s*데이터와\s*보조\s*분석\s*데이터의\s*기준\s*시점이\s*다를\s*수\s*있어\s*freshness\s*정보를\s*함께\s*표시합니다\./g, "Price data and overlay analysis data may have different reference times, so freshness information is shown together."],
  [/상장시장\s*정보를\s*확인하지\s*못해\s*KOSPI\s*벤치마크를\s*대체\s*기준으로\s*사용합니다\./g, "Market-listing information could not be verified, so KOSPI is used as a proxy benchmark."],
  [/KOSPI\/KOSDAQ\s*종목이\s*함께\s*있어\s*상장시장별\s*벤치마크로\s*CAPM을\s*계산합니다\./g, "Because KOSPI and KOSDAQ holdings are mixed, CAPM is calculated with market-specific benchmarks."],
  [/상장시장별\s*벤치마크를\s*분리해\s*CAPM을\s*계산했습니다\./g, "CAPM was calculated with separate benchmarks by listing market."],
  [/고급\s*검증의\s*기대수익률은\s*과거\s*수익률과\s*CAPM\s*추정치를\s*데이터\s*신뢰도에\s*따라\s*혼합한\s*값이라\s*실제\s*수익\s*예측으로\s*해석하면\s*안\s*됩니다\./g, "The advanced expected return blends historical returns and CAPM estimates based on data confidence; it should not be interpreted as an actual return forecast."],
  [/가격\s*데이터가\s*부족해\s*일부\s*결과는\s*임시\s*기준으로\s*표시됩니다\./g, "Some results are shown on a temporary basis because price data is insufficient."],
  [/가격\s*움직임\s*계산\s*중\s*안정화\s*모델을\s*적용하지\s*못해\s*대체\s*계산값을\s*사용했습니다\./g, "A fallback calculation was used because the stabilization model could not be applied while calculating price movements."],
  [/가격\s*데이터\s*품질\s*기준을\s*충족한\s*종목이\s*없어\s*현재\s*입력\s*비중\s*기반으로\s*표시됩니다\./g, "No holdings met the price-data quality criteria, so the result is shown based on current input weights."],
  [/공통\s*수익률\s*표본이\s*부족해\s*현재\s*입력\s*비중\s*기반으로\s*표시됩니다\./g, "Common return samples are insufficient, so the result is shown based on current input weights."],
  [/공통\s*수익률\s*표본에\s*유효하지\s*않은\s*값이\s*있어\s*현재\s*입력\s*비중\s*기반으로\s*표시됩니다\./g, "The common return sample contains invalid values, so the result is shown based on current input weights."],
  [/일부\s*종목은\s*가격\s*데이터\s*품질\s*기준을\s*충족하지\s*못해\s*핵심\s*리스크\s*계산에서\s*제외됐습니다\./g, "Some holdings were excluded from core risk calculations because they did not meet price-data quality criteria."],
  [/유사\s*종목군/g, "peer group"],
  [/유사\s*종목/g, "peer stocks"],
  [/보조\s*관측/g, "overlay observations"],
  [/최적화\s*관측/g, "optimization view"],
  [/핵심\s*리스크/g, "core risk"],
  [/현재\s*포트폴리오/g, "current portfolio"],
  [/현재\s*구성/g, "current portfolio"],
  [/가격\s*시계열/g, "price series"],
  [/포트폴리오\s*분석/g, "portfolio analysis"],
  [/분산\s*리스크/g, "diversification risk"],
  [/위험\s*기여도/g, "risk contribution"],
  [/투자\s*성향/g, "risk profile"],
  [/목표\s*변동성/g, "target volatility"],
  [/변동성/g, "volatility"],
  [/종목\s*건강도/g, "stock quality"],
  [/확대\s*압력/g, "expansion pressure"],
  [/관찰\s*압력/g, "observation pressure"],
  [/동행\s*참고/g, "co-movement reference"],
  [/관찰\s*압력/g, "observation pressure"],
  [/삼성전자/g, "Samsung Electronics"],
  [/SK하이닉스/g, "SK hynix"],
  [/KRW\s*현금/g, "KRW cash"],
  [/현금/g, "cash"],
  [/공격적/g, "aggressive"],
  [/안정적/g, "conservative"],
  [/중립형/g, "balanced"],
  [/공격형/g, "aggressive"],
  [/보수형/g, "conservative"],
  [/균형형/g, "balanced"],
  [/기준\s*시각/g, "reference time"],
  [/최근\s*결과/g, "recent result"],
  [/새로\s*분석/g, "re-analyze"],
  [/새\s*분석/g, "new analysis"],
  [/기존\s*source\s*data/g, "existing source data"],
  [/원천\s*데이터/g, "source data"],
  [/업종\s*정보/g, "industry information"],
  [/산업\s*집중도\s*관측/g, "industry concentration observation"],
  [/산업\s*지수/g, "industry index"],
  [/산업지수/g, "industry index"],
  [/유사종목/g, "peer stocks"],
  [/캐시/g, "cache"],
  [/크레딧/g, "credit"],
  [/성향보다 공격적/g, "more aggressive than profile"],
  [/성향보다 안정적/g, "more conservative than profile"],
  [/목표 변동성 초과/g, "above target volatility"],
  [/위험 기여도 높음/g, "high risk contribution"],
  [/\bAGGRESSIVE_THAN_PROFILE\b/g, "more aggressive than profile"],
  [/\bCONSERVATIVE_THAN_PROFILE\b/g, "more conservative than profile"],
  [/\bABOVE_TARGET_VOLATILITY\b/g, "above target volatility"],
  [/\bHIGH_RISK_CONTRIBUTION\b/g, "high risk contribution"],
  [/Core 분석만 실행하면 1 credit이 차감됩니다\./g, "Running core analysis only deducts 1 credit."],
  [/Core 분석은 1 credit이며, cache가 없는 체크 항목마다 1 credit이 추가됩니다\./g, "Core analysis costs 1 credit, and each selected item without cache adds 1 credit."],
  [/Core analysis costs 1 credit이며, cache가 없는 체크 항목마다 1 credit이 추가됩니다\./g, "Core analysis costs 1 credit, and each selected item without cache adds 1 credit."],
  [/최근 result가 있지만 re-analyze하도록 선택되어 1 credit이 추가됩니다\./g, "A recent result exists, but re-analysis was selected, so 1 credit is added."],
  [/최근 결과가 있지만 새로 분석하도록 선택되어 1 credit이 추가됩니다\./g, "A recent result exists, but re-analysis was selected, so 1 credit is added."],
  [/기존 source data를 재사용할 수 있어 추가 credit이 필요하지 않습니다\./g, "Existing source data can be reused, so no additional credit is required."],
  [/기존 원천 데이터를 재사용할 수 있어 추가 credit이 필요하지 않습니다\./g, "Existing source data can be reused, so no additional credit is required."],
  [/원천 데이터가 부족해 새로 분석하며 1 credit이 추가됩니다\./g, "Source data is insufficient, so new analysis adds 1 credit."],
  [/보유 종목의 업종 정보를 사용해 산업 집중도 관측을 반영합니다\./g, "Uses the holdings' industry information to reflect industry concentration observations."],
  [/최근 뉴스 최대 (\d+)개의 Feature2 news sentiment 데이터를 core risk와 분리된 뉴스 흐름 참고 정보로 표시합니다\./g, "Shows up to $1 recent Feature2 news sentiment items as separate news-flow context, outside core risk."],
  [/current portfolio의/g, "current portfolio's"],
  [/current portfolio's\s*가격\s*변동\s*폭이\s*risk profile\s*기준보다\s*큽니다\./g, "The current portfolio's price volatility is higher than the risk-profile benchmark."],
  [/current portfolio은\s*risk profile\s*기준보다\s*conservative으로\s*움직이는\s*편입니다\./g, "The current portfolio is moving more conservatively than the risk-profile benchmark."],
  [/current portfolio의\s*volatility\s*risk이\s*risk profile\s*기준과\s*크게\s*벗어나지\s*않습니다\./g, "The current portfolio's volatility risk is broadly aligned with the risk-profile benchmark."],
  [/Samsung Electronics\s*비중이\s*전체\s*risk contribution에서\s*차지하는\s*몫이\s*큽니다\./g, "Samsung Electronics accounts for a large share of total risk contribution."],
];

export function localizeBackendText(value?: string | null, language?: string | null): string {
  if (!value) return "";
  if (!isEnglishLanguage(language)) return value;
  return EN_BACKEND_TEXT_REPLACEMENTS.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}
